defaultPortal: staging
environment: staging
portals:
  - name: staging
    portalId: ${{ secrets.hubspot_portal_id }}
    authType: personalaccesskey
    personalAccessKey: >-
      ${{ secrets.hubspot_personal_access_key }}


    auth:
      tokenInfo:
        accessToken: >-
          ${{ secrets.hubspot_personal_access_key }}


        expiresAt: '2024-07-12T15:54:24.944Z'
