name: Prepare Action Runner
author: Institute for Integrative Nutrition
description: Prepare an action runner
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "20.x"
