on:
  push:
    branches:
    - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: themes
          dest_dir: .
          portal_id: ${{ secrets.portal_id }}
          personal_access_key: ${{ secrets.personal_access_key }}
