on:
  push:
    branches:
    - staging
jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Deploy theme
        uses:  ./.github/actions/deploy
        with:
          src_dir: themes
          dest_dir: .
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
      - name: Write Staging app config
        uses:  ./.github/actions/deploy
        with:
          src_dir: './themes/Integrative Nutrition/macros/get-app-config.staging.html'
          dest_dir: '/Integrative Nutrition/macros/get-app-config.html'
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
