on:
  push:
    branches:
    - staging
jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Deploy theme
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: themes
          dest_dir: .
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
      - name: Write Staging app config
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: "./themes/Integrative Nutrition/macros/get-app-config.staging.html"
          dest_dir: "/Integrative Nutrition/macros/get-app-config.html"
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
